#!/bin/bash -e

pushd submodules/LibreChat

docker compose \
    --env-file ../../config/libre-chat.env \
    -f docker-compose.yml \
    -f ../../config/libre-chat.docker-compose.override.yml \
    down "$@"

popd